const data = [
	{
		MatchNumber: 2,
		RoundNumber: 1,
		DateUtc: '2022-11-21 16:00:00Z',
		Location: 'Al Thumama',
		HomeTeam: 'Senegal',
		AwayTeam: 'Paises Bajos',
		Group: 'Grupo A',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 3,
		RoundNumber: 1,
		DateUtc: '2022-11-21 13:00:00Z',
		Location: 'Khalifa Int.',
		HomeTeam: 'Inglaterra',
		AwayTeam: 'Iran',
		Group: 'Grupo B',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 1,
		RoundNumber: 1,
		DateUtc: '2022-11-20 16:00:00Z',
		Location: 'Al Bayt',
		HomeTeam: 'Qatar',
		AwayTeam: 'Ecuador',
		Group: 'Grupo A',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 4,
		RoundNumber: 1,
		DateUtc: '2022-11-21 19:00:00Z',
		Location: 'Ahmad Bin Ali',
		HomeTeam: 'USA',
		AwayTeam: 'Gales',
		Group: 'Grupo B',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 8,
		RoundNumber: 1,
		DateUtc: '2022-11-22 10:00:00Z',
		Location: 'Lusail',
		HomeTeam: 'Argentina',
		AwayTeam: 'Arabia Saudita',
		Group: 'Grupo C',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 6,
		RoundNumber: 1,
		DateUtc: '2022-11-22 13:00:00Z',
		Location: 'Education City',
		HomeTeam: 'Dinamarca',
		AwayTeam: 'Túnez',
		Group: 'Grupo D',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 7,
		RoundNumber: 1,
		DateUtc: '2022-11-22 16:00:00Z',
		Location: 'Stadium 974',
		HomeTeam: 'México',
		AwayTeam: 'Polonia',
		Group: 'Grupo C',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 5,
		RoundNumber: 1,
		DateUtc: '2022-11-22 19:00:00Z',
		Location: 'Al Janoub',
		HomeTeam: 'Francia',
		AwayTeam: 'Australia',
		Group: 'Grupo D',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 12,
		RoundNumber: 1,
		DateUtc: '2022-11-23 10:00:00Z',
		Location: 'Al Bayt',
		HomeTeam: 'Marruecos',
		AwayTeam: 'Croacia',
		Group: 'Grupo F',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 11,
		RoundNumber: 1,
		DateUtc: '2022-11-23 13:00:00Z',
		Location: 'Khalifa Int.',
		HomeTeam: 'Alemania',
		AwayTeam: 'Japón',
		Group: 'Grupo E',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 10,
		RoundNumber: 1,
		DateUtc: '2022-11-23 16:00:00Z',
		Location: 'Al Thumama',
		HomeTeam: 'España',
		AwayTeam: 'Costa Rica',
		Group: 'Grupo E',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 9,
		RoundNumber: 1,
		DateUtc: '2022-11-23 19:00:00Z',
		Location: 'Ahmad Bin Ali',
		HomeTeam: 'Bélgica',
		AwayTeam: 'Canada',
		Group: 'Grupo F',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 13,
		RoundNumber: 1,
		DateUtc: '2022-11-24 10:00:00Z',
		Location: 'Al Janoub',
		HomeTeam: 'Suiza',
		AwayTeam: 'Camerún',
		Group: 'Grupo G',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 14,
		RoundNumber: 1,
		DateUtc: '2022-11-24 13:00:00Z',
		Location: 'Education City',
		HomeTeam: 'Uruguay',
		AwayTeam: 'Corea del Sur',
		Group: 'Grupo H',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 15,
		RoundNumber: 1,
		DateUtc: '2022-11-24 16:00:00Z',
		Location: 'Stadium 974',
		HomeTeam: 'Portugal',
		AwayTeam: 'Ghana',
		Group: 'Grupo H',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 16,
		RoundNumber: 1,
		DateUtc: '2022-11-24 19:00:00Z',
		Location: 'Lusail',
		HomeTeam: 'Brasil',
		AwayTeam: 'Serbia',
		Group: 'Grupo G',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 17,
		RoundNumber: 2,
		DateUtc: '2022-11-25 10:00:00Z',
		Location: 'Ahmad Bin Ali',
		HomeTeam: 'Gales',
		AwayTeam: 'Iran',
		Group: 'Grupo B',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 18,
		RoundNumber: 2,
		DateUtc: '2022-11-25 13:00:00Z',
		Location: 'Al Thumama',
		HomeTeam: 'Qatar',
		AwayTeam: 'Senegal',
		Group: 'Grupo A',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 19,
		RoundNumber: 2,
		DateUtc: '2022-11-25 16:00:00Z',
		Location: 'Khalifa Int.',
		HomeTeam: 'Paises Bajos',
		AwayTeam: 'Ecuador',
		Group: 'Grupo A',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 20,
		RoundNumber: 2,
		DateUtc: '2022-11-25 19:00:00Z',
		Location: 'Al Bayt',
		HomeTeam: 'Inglaterra',
		AwayTeam: 'USA',
		Group: 'Grupo B',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 21,
		RoundNumber: 2,
		DateUtc: '2022-11-26 10:00:00Z',
		Location: 'Al Janoub',
		HomeTeam: 'Túnez',
		AwayTeam: 'Australia',
		Group: 'Grupo D',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 22,
		RoundNumber: 2,
		DateUtc: '2022-11-26 13:00:00Z',
		Location: 'Education City',
		HomeTeam: 'Polonia',
		AwayTeam: 'Arabia Saudita',
		Group: 'Grupo C',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 23,
		RoundNumber: 2,
		DateUtc: '2022-11-26 16:00:00Z',
		Location: 'Stadium 974',
		HomeTeam: 'Francia',
		AwayTeam: 'Dinamarca',
		Group: 'Grupo D',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 24,
		RoundNumber: 2,
		DateUtc: '2022-11-26 19:00:00Z',
		Location: 'Lusail',
		HomeTeam: 'Argentina',
		AwayTeam: 'México',
		Group: 'Grupo C',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 25,
		RoundNumber: 2,
		DateUtc: '2022-11-27 10:00:00Z',
		Location: 'Ahmad Bin Ali',
		HomeTeam: 'Japón',
		AwayTeam: 'Costa Rica',
		Group: 'Grupo E',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 26,
		RoundNumber: 2,
		DateUtc: '2022-11-27 13:00:00Z',
		Location: 'Al Thumama',
		HomeTeam: 'Bélgica',
		AwayTeam: 'Marruecos',
		Group: 'Grupo F',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 27,
		RoundNumber: 2,
		DateUtc: '2022-11-27 16:00:00Z',
		Location: 'Khalifa Int.',
		HomeTeam: 'Croacia',
		AwayTeam: 'Canada',
		Group: 'Grupo F',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 28,
		RoundNumber: 2,
		DateUtc: '2022-11-27 19:00:00Z',
		Location: 'Al Bayt',
		HomeTeam: 'España',
		AwayTeam: 'Alemania',
		Group: 'Grupo E',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 29,
		RoundNumber: 2,
		DateUtc: '2022-11-28 10:00:00Z',
		Location: 'Al Janoub',
		HomeTeam: 'Camerún',
		AwayTeam: 'Serbia',
		Group: 'Grupo G',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 30,
		RoundNumber: 2,
		DateUtc: '2022-11-28 13:00:00Z',
		Location: 'Education City',
		HomeTeam: 'Corea del Sur',
		AwayTeam: 'Ghana',
		Group: 'Grupo H',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 31,
		RoundNumber: 2,
		DateUtc: '2022-11-28 16:00:00Z',
		Location: 'Stadium 974',
		HomeTeam: 'Brasil',
		AwayTeam: 'Suiza',
		Group: 'Grupo G',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 32,
		RoundNumber: 2,
		DateUtc: '2022-11-28 19:00:00Z',
		Location: 'Lusail',
		HomeTeam: 'Portugal',
		AwayTeam: 'Uruguay',
		Group: 'Grupo H',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 35,
		RoundNumber: 3,
		DateUtc: '2022-11-29 15:00:00Z',
		Location: 'Khalifa Int.',
		HomeTeam: 'Ecuador',
		AwayTeam: 'Senegal',
		Group: 'Grupo A',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 36,
		RoundNumber: 3,
		DateUtc: '2022-11-29 15:00:00Z',
		Location: 'Al Bayt',
		HomeTeam: 'Paises Bajos',
		AwayTeam: 'Qatar',
		Group: 'Grupo A',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 33,
		RoundNumber: 3,
		DateUtc: '2022-11-29 19:00:00Z',
		Location: 'Ahmad Bin Ali',
		HomeTeam: 'Gales',
		AwayTeam: 'Inglaterra',
		Group: 'Grupo B',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 34,
		RoundNumber: 3,
		DateUtc: '2022-11-29 19:00:00Z',
		Location: 'Al Thumama',
		HomeTeam: 'Iran',
		AwayTeam: 'USA',
		Group: 'Grupo B',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 37,
		RoundNumber: 3,
		DateUtc: '2022-11-30 15:00:00Z',
		Location: 'Al Janoub',
		HomeTeam: 'Australia',
		AwayTeam: 'Dinamarca',
		Group: 'Grupo D',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 38,
		RoundNumber: 3,
		DateUtc: '2022-11-30 15:00:00Z',
		Location: 'Education City',
		HomeTeam: 'Túnez',
		AwayTeam: 'Francia',
		Group: 'Grupo D',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 39,
		RoundNumber: 3,
		DateUtc: '2022-11-30 19:00:00Z',
		Location: 'Stadium 974',
		HomeTeam: 'Polonia',
		AwayTeam: 'Argentina',
		Group: 'Grupo C',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 40,
		RoundNumber: 3,
		DateUtc: '2022-11-30 19:00:00Z',
		Location: 'Lusail',
		HomeTeam: 'Arabia Saudita',
		AwayTeam: 'México',
		Group: 'Grupo C',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 41,
		RoundNumber: 3,
		DateUtc: '2022-12-01 15:00:00Z',
		Location: 'Ahmad Bin Ali',
		HomeTeam: 'Croacia',
		AwayTeam: 'Bélgica',
		Group: 'Grupo F',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 42,
		RoundNumber: 3,
		DateUtc: '2022-12-01 15:00:00Z',
		Location: 'Al Thumama',
		HomeTeam: 'Canada',
		AwayTeam: 'Marruecos',
		Group: 'Grupo F',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 43,
		RoundNumber: 3,
		DateUtc: '2022-12-01 19:00:00Z',
		Location: 'Khalifa Int.',
		HomeTeam: 'Japón',
		AwayTeam: 'España',
		Group: 'Grupo E',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 44,
		RoundNumber: 3,
		DateUtc: '2022-12-01 19:00:00Z',
		Location: 'Al Bayt',
		HomeTeam: 'Costa Rica',
		AwayTeam: 'Alemania',
		Group: 'Grupo E',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 45,
		RoundNumber: 3,
		DateUtc: '2022-12-02 15:00:00Z',
		Location: 'Al Janoub',
		HomeTeam: 'Ghana',
		AwayTeam: 'Uruguay',
		Group: 'Grupo H',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 46,
		RoundNumber: 3,
		DateUtc: '2022-12-02 15:00:00Z',
		Location: 'Education City',
		HomeTeam: 'Corea del Sur',
		AwayTeam: 'Portugal',
		Group: 'Grupo H',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 47,
		RoundNumber: 3,
		DateUtc: '2022-12-02 19:00:00Z',
		Location: 'Stadium 974',
		HomeTeam: 'Serbia',
		AwayTeam: 'Suiza',
		Group: 'Grupo G',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 48,
		RoundNumber: 3,
		DateUtc: '2022-12-02 19:00:00Z',
		Location: 'Lusail',
		HomeTeam: 'Camerún',
		AwayTeam: 'Brasil',
		Group: 'Grupo G',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 49,
		RoundNumber: 4,
		DateUtc: '2022-12-03 15:00:00Z',
		Location: 'Khalifa Int.',
		HomeTeam: '1A',
		AwayTeam: '2B',
		Group: 'Octavos',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 50,
		RoundNumber: 4,
		DateUtc: '2022-12-03 19:00:00Z',
		Location: 'Ahmad Bin Ali',
		HomeTeam: '1C',
		AwayTeam: '2D',
		Group: 'Octavos',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 52,
		RoundNumber: 4,
		DateUtc: '2022-12-04 15:00:00Z',
		Location: 'Al Thumama',
		HomeTeam: '1D',
		AwayTeam: '2C',
		Group: 'Octavos',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 51,
		RoundNumber: 4,
		DateUtc: '2022-12-04 19:00:00Z',
		Location: 'TBA',
		HomeTeam: '1B',
		AwayTeam: '2A',
		Group: 'Octavos',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 53,
		RoundNumber: 4,
		DateUtc: '2022-12-05 15:00:00Z',
		Location: 'TBA',
		HomeTeam: '1E',
		AwayTeam: '2F',
		Group: 'Octavos',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 54,
		RoundNumber: 4,
		DateUtc: '2022-12-05 19:00:00Z',
		Location: 'Stadium 974',
		HomeTeam: '1G',
		AwayTeam: '2H',
		Group: 'Octavos',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 55,
		RoundNumber: 4,
		DateUtc: '2022-12-06 15:00:00Z',
		Location: 'TBA',
		HomeTeam: '1F',
		AwayTeam: '2E',
		Group: 'Octavos',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 56,
		RoundNumber: 4,
		DateUtc: '2022-12-06 19:00:00Z',
		Location: 'Lusail',
		HomeTeam: '1H',
		AwayTeam: '2G',
		Group: 'Octavos',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 58,
		RoundNumber: 5,
		DateUtc: '2022-12-09 15:00:00Z',
		Location: 'Education City',
		HomeTeam: 'To be announced',
		AwayTeam: 'To be announced',
		Group: 'Cuartos',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 57,
		RoundNumber: 5,
		DateUtc: '2022-12-09 19:00:00Z',
		Location: 'Lusail',
		HomeTeam: 'To be announced',
		AwayTeam: 'To be announced',
		Group: 'Cuartos',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 60,
		RoundNumber: 5,
		DateUtc: '2022-12-10 15:00:00Z',
		Location: 'Al Thumama',
		HomeTeam: 'To be announced',
		AwayTeam: 'To be announced',
		Group: 'Cuartos',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 59,
		RoundNumber: 5,
		DateUtc: '2022-12-10 19:00:00Z',
		Location: 'Al Bayt',
		HomeTeam: 'To be announced',
		AwayTeam: 'To be announced',
		Group: 'Cuartos',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 61,
		RoundNumber: 6,
		DateUtc: '2022-12-13 19:00:00Z',
		Location: 'Lusail',
		HomeTeam: 'To be announced',
		AwayTeam: 'To be announced',
		Group: 'Semifinal',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 62,
		RoundNumber: 6,
		DateUtc: '2022-12-14 19:00:00Z',
		Location: 'Al Bayt',
		HomeTeam: 'To be announced',
		AwayTeam: 'To be announced',
		Group: 'Semifinal',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 63,
		RoundNumber: 7,
		DateUtc: '2022-12-17 15:00:00Z',
		Location: 'Khalifa Int.',
		HomeTeam: 'To be announced',
		AwayTeam: 'To be announced',
		Group: 'Tercer Puesto',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
	{
		MatchNumber: 64,
		RoundNumber: 7,
		DateUtc: '2022-12-18 15:00:00Z',
		Location: 'Lusail',
		HomeTeam: 'To be announced',
		AwayTeam: 'To be announced',
		Group: 'Final',
		HomeTeamScore: null,
		AwayTeamScore: null,
	},
];

export default data;
