import Head from 'next/head';
import Group from '../components/Group';
import styles from '../styles/Home.module.css';
import HeaderGroup from '../components/HeaderGroup';
import InfoMatch from '../components/InfoMatch';
import MatchGroup from '../components/MatchGroup';
import TeamsMatch from '../components/TeamsMatch';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Fixture Mundial Qatar 2022</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<h1>
					<a>Fixture Mundial Qatar 2022</a>
				</h1>
				<Group>
					<HeaderGroup grupo={'A'} equipos={'🇶🇦 🇪🇨 🇨🇲 🇳🇱'} />
					<MatchGroup>
						<InfoMatch />
						<TeamsMatch />
					</MatchGroup>
					<MatchGroup>
						<InfoMatch />
						<TeamsMatch />
					</MatchGroup>
				</Group>
				<Group>
					<HeaderGroup grupo={'B'} equipos={'🏴󠁧󠁢󠁥󠁮󠁧󠁿 🇮🇷 🇺🇸 🏴󠁧󠁢󠁷󠁬󠁳󠁿'} />
					<MatchGroup>
						<InfoMatch />
						<TeamsMatch />
					</MatchGroup>
				</Group>
			</main>
		</div>
	);
}
