import { useEffect, useState } from 'react';
import Head from 'next/head';

import Group from '../components/Group';
import styles from '../styles/Home.module.css';
import HeaderGroup from '../components/HeaderGroup';
import InfoMatch from '../components/InfoMatch';
import MatchGroup from '../components/MatchGroup';
import TeamsMatch from '../components/TeamsMatch';

export default function Home() {
	const [matches, setMatches] = useState([]);

	useEffect(() => {
		window
			.fetch('/api/')
			.then((res) => res.json())
			.then(({ data }) => {
				setMatches(data);
			});
	}, []);

	const conjuntoGrupos = [];
	matches.map(({ Group }) => conjuntoGrupos.push(Group));

	const sinDuplicados = [...new Set(conjuntoGrupos)];

	console.log(sinDuplicados);

	return (
		<div>
			<Head>
				<title>Fixture Mundial Qatar 2022</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<h1>
					<a>Fixture Mundial Qatar 2022</a>
				</h1>
				{sinDuplicados.map((grupos) => (
					<div key={grupos}>
						<h2>{grupos}</h2>
					</div>
				))}
				{/* <Group>
					<HeaderGroup grupo={'A'} equipos={'🇶🇦 🇪🇨 🇨🇲 🇳🇱'} />
					<MatchGroup>
						<InfoMatch />
						<TeamsMatch />
					</MatchGroup>
				</Group>
				<Group>
					<HeaderGroup grupo={'B'} equipos={'🏴󠁧󠁢󠁥󠁮󠁧󠁿 🇮🇷 🇺🇸 🏴󠁧󠁢󠁷󠁬󠁳󠁿'} />
					<MatchGroup>
						<InfoMatch />
						<TeamsMatch />
					</MatchGroup>
				</Group> */}
			</main>
		</div>
	);
}
