import { useEffect, useState } from 'react';
import Head from 'next/head';
import Group from '../components/Group';
import HeaderGroup from '../components/HeaderGroup';
import InfoMatch from '../components/InfoMatch';
import MatchGroup from '../components/MatchGroup';
import TeamsMatch from '../components/TeamsMatch';
import styles from '../styles/Home.module.css';

export default function Home() {
	const [matches, setMatches] = useState([]);

	useEffect(() => {
		window
			.fetch('/api/')
			.then((res) => res.json())
			.then(({ data }) => {
				setMatches(data);
			});
	}, []);

	const allGroups = [];
	matches.map(({ Group }) => allGroups.push(Group));
	const groupList = [...new Set(allGroups)];

	return (
		<div>
			<Head>
				<title>Fixture Mundial Qatar 2022</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1, maximum-scale=1'
				></meta>
			</Head>
			<main>
				<h1>
					<a>Fixture Mundial Qatar 2022</a>
				</h1>
				{groupList.map((groups) => (
					<section key={groups} className={styles.groups}>
						<Group matches={matches} group={groups} />
					</section>
				))}
				{/* <Group>
					<HeaderGroup grupo={'A'} equipos={'🇶🇦 🇪🇨 🇨🇲 🇳🇱'} />
					<MatchGroup>
						<InfoMatch />
						<TeamsMatch />
					</MatchGroup>
				</Group> */}
			</main>
		</div>
	);
}
